services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8008:8000"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8008
    ports:
      - "3000:80"
    depends_on:
      - backend
